# Generated by Django 5.2.5 on 2025-09-12 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        max_length=10,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_lecture", "Create Lecture"),
                            ("create_assignment", "Create Assignment"),
                            ("submit_assignment", "Submit Assignment"),
                            ("grade_assignment", "Grade Assignment"),
                            ("post_announcement", "Post Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_id", models.IntegerField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("assignment", "Assignment"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
