# Generated by Django 5.2.4 on 2025-08-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('action_type', models.CharField(choices=[('create_lecture', 'Create Lecture'), ('create_assignment', 'Create Assignment'), ('submit_assignment', 'Submit Assignment'), ('grade_assignment', 'Grade Assignment'), ('post_announcement', 'Post Announcement')], max_length=30)),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(choices=[('lecture', 'Lecture'), ('assignment', 'Assignment'), ('announcement', 'Announcement')], max_length=20)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
