# Generated by Django 5.2.4 on 2025-08-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('new_assignment', 'New Assignment'), ('assignment_graded', 'Assignment Graded'), ('new_announcement', 'New Announcement'), ('new_lecture', 'New Lecture')], max_length=50)),
                ('target_type', models.CharField(choices=[('assignment', 'Assignment'), ('lecture', 'Lecture'), ('announcement', 'Announcement')], max_length=50)),
                ('target_id', models.IntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
