# Generated by Django 5.2.5 on 2025-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_remove_lecture_level_alter_teacher_user_delete_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
