# Generated by Django 5.2.5 on 2025-09-03 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0003_alter_lecture_pdf_url_alter_lecture_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="pdf_url",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lecture",
            name="pdf",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="pdf"
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
