# Generated by Django 5.2.5 on 2025-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0004_remove_lecture_pdf_url_remove_lecture_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="Mr. S", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
