# Generated by Django 5.2.5 on 2025-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0005_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="Mr. S", max_length=100, unique=True),
        ),
    ]
