# Generated by Django 5.2.5 on 2025-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0006_alter_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
