# Generated by Django 5.2.5 on 2025-08-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("new_assignment", "New Assignment"),
                            ("assignment_graded", "Assignment Graded"),
                            ("new_announcement", "New Announcement"),
                            ("new_lecture", "New Lecture"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("lecture", "Lecture"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.IntegerField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
